KERNAL_CHROUT EQU $FFD2
KERNAL_PLOT	  EQU $FFF0
KERNAL_SETNAM EQU $FFBD
KERNAL_SETLFS EQU $FFBA
KERNAL_OPEN   EQU $FFC0
KERNAL_READST EQU $FFB7
KERNAL_CLOSE  EQU $FFC3
KERNAL_GETIN  EQU $FFE4
KERNAL_CLALL  EQU $FFE7
KERNAL_CHRIN  EQU $FFCF
KERNAL_CHKIN  EQU $FFC6
KERNAL_CHKOUT EQU $FFC9
KERNAL_CLRCHN EQU $FFCC
KERNAL_LOAD	  EQU $FFD5
	IF TARGET & pet
		IF TARGET == pet2001
KERNAL_SAVE   EQU $F6B1
		ENDIF
		IF TARGET & pet3
KERNAL_SAVE   EQU $F6A4
		ENDIF
		IF TARGET & pet4
KERNAL_SAVE	  EQU $F6E3
		ENDIF
	ELSE
KERNAL_SAVE   EQU $FFD8
	ENDIF
KERNAL_SCREENMODE EQU $FF5F ; Commander X16 only
X16_screen_set_charset EQU $FF62 ; Commander X16 only

	; Calls a KERNAL routine
	; Routine address in {1}
	MAC kerncall
	jsr {1}
	ENDM