KERNAL_CHROUT EQU $FFD2
KERNAL_PLOT	  EQU $FFF0
KERNAL_SETNAM EQU $FFBD
KERNAL_SETLFS EQU $FFBA
KERNAL_OPEN   EQU $FFC0
KERNAL_READST EQU $FFB7
KERNAL_CLOSE  EQU $FFC3
KERNAL_GETIN  EQU $FFE4
KERNAL_CHRIN  EQU $FFCF
KERNAL_CHKIN  EQU $FFC6
KERNAL_CHKOUT EQU $FFC9
KERNAL_CLRCHN EQU $FFCC
KERNAL_LOAD	  EQU $FFD5
KERNAL_SAVE   EQU $FFD8
STATUS EQU $90 ; KERNAL I/O STATUS

	; Calls a KERNAL routine
	; Routine address in {1}
	MAC kerncall
	jsr {1}
	ENDM