' Tests arithmetic operations on DECIMALs in XC=BASIC
' MONITOR: m c000 c0ff
' DECIMAL is a 16-bit unsigned BCD number (0000..9999), only + and - are supported

' This page will be used to compare the results against the golden set
DIM results(127) AS DECIMAL @ $C000
DIM a AS DECIMAL, b AS DECIMAL
DIM acc AS DECIMAL, stp AS DECIMAL
DIM i AS BYTE

' 0..15   : addition, explicit carry boundary cases
' 16..31  : subtraction, explicit borrow boundary cases
' 32..79  : addition, generated by repeated accumulation
' 80..127 : subtraction, generated by repeated accumulation

' Addition: carry boundaries between BCD digits, and wraparound at 10000
a = 0d : b = 0d          : results(0)  = a + b   ' zero+zero
a = 0d : b = 1d          : results(1)  = a + b   ' zero+one
a = 1d : b = 0d          : results(2)  = a + b   ' one+zero
a = 9d : b = 1d          : results(3)  = a + b   ' carry into tens digit
a = 99d : b = 1d         : results(4)  = a + b   ' carry into hundreds digit
a = 999d : b = 1d        : results(5)  = a + b   ' carry into thousands digit
a = 9999d : b = 1d       : results(6)  = a + b   ' full wraparound
a = 9998d : b = 1d       : results(7)  = a + b   ' just below wraparound boundary
a = 4999d : b = 1d       : results(8)  = a + b   ' carry mid-value
a = 5000d : b = 5000d    : results(9)  = a + b   ' exact wraparound boundary
a = 4999d : b = 5000d    : results(10) = a + b   ' just below wraparound boundary
a = 1234d : b = 8766d    : results(11) = a + b   ' wraparound, arbitrary values
a = 1234d : b = 8765d    : results(12) = a + b   ' no wraparound, arbitrary values
a = 45d : b = 55d        : results(13) = a + b   ' two-digit carry chain
a = 999d : b = 999d      : results(14) = a + b   ' multi-digit carry, no wraparound
a = 9000d : b = 1000d    : results(15) = a + b   ' wraparound, round numbers

' Subtraction: borrow boundaries between BCD digits, and underflow wraparound
a = 0d : b = 0d          : results(16) = a - b   ' zero-zero
a = 1d : b = 0d          : results(17) = a - b   ' one-zero
a = 0d : b = 1d          : results(18) = a - b   ' underflow wraparound
a = 10d : b = 1d         : results(19) = a - b   ' borrow from tens digit
a = 100d : b = 1d        : results(20) = a - b   ' borrow from hundreds digit
a = 1000d : b = 1d       : results(21) = a - b   ' borrow from thousands digit
a = 9999d : b = 9999d    : results(22) = a - b   ' max-max, zero
a = 9999d : b = 1d       : results(23) = a - b   ' near max, no underflow
a = 5000d : b = 5000d    : results(24) = a - b   ' equal operands, zero
a = 5000d : b = 1d       : results(25) = a - b   ' borrow chain
a = 2d : b = 3d          : results(26) = a - b   ' underflow by one
a = 9000d : b = 9001d    : results(27) = a - b   ' underflow near boundary
a = 100d : b = 99d       : results(28) = a - b   ' no borrow, small diff
a = 100d : b = 100d      : results(29) = a - b   ' equal operands, zero
a = 45d : b = 55d        : results(30) = a - b   ' underflow with two-digit borrow
a = 1000d : b = 999d     : results(31) = a - b   ' borrow across three-digit boundary

' Addition: filler generated by repeated accumulation (wraps several times)
acc = 137d : stp = 271d
FOR i = 0 TO 47
	acc = acc + stp
	results(32 + i) = acc
NEXT i

' Subtraction: filler generated by repeated accumulation (wraps several times)
acc = 9999d : stp = 271d
FOR i = 0 TO 47
	acc = acc - stp
	results(80 + i) = acc
NEXT i
