' Tests arithmetic operations on FAST DECIMAL arrays in XC=BASIC
' MONITOR: m c000 c0ff
' DECIMAL is a 16-bit unsigned BCD number (0000..9999), only + and - are supported

' This page will be used to compare the results against the golden set
DIM results(127) AS DECIMAL @ $C000
DIM myarr(5) AS DECIMAL FAST
DIM i AS BYTE FAST

' 0..15   : addition, explicit carry boundary cases
' 16..31  : subtraction, explicit borrow boundary cases
' 32..79  : addition, generated by repeated accumulation
' 80..127 : subtraction, generated by repeated accumulation

' Addition: carry boundaries between BCD digits, and wraparound at 10000
myarr(1) = 0d : myarr(2) = 0d          : results(0)  = myarr(1) + myarr(2)   ' zero+zero
myarr(1) = 0d : myarr(2) = 1d          : results(1)  = myarr(1) + myarr(2)   ' zero+one
myarr(1) = 1d : myarr(2) = 0d          : results(2)  = myarr(1) + myarr(2)   ' one+zero
myarr(1) = 9d : myarr(2) = 1d          : results(3)  = myarr(1) + myarr(2)   ' carry into tens digit
myarr(1) = 99d : myarr(2) = 1d         : results(4)  = myarr(1) + myarr(2)   ' carry into hundreds digit
myarr(1) = 999d : myarr(2) = 1d        : results(5)  = myarr(1) + myarr(2)   ' carry into thousands digit
myarr(1) = 9999d : myarr(2) = 1d       : results(6)  = myarr(1) + myarr(2)   ' full wraparound
myarr(1) = 9998d : myarr(2) = 1d       : results(7)  = myarr(1) + myarr(2)   ' just below wraparound boundary
myarr(1) = 4999d : myarr(2) = 1d       : results(8)  = myarr(1) + myarr(2)   ' carry mid-value
myarr(1) = 5000d : myarr(2) = 5000d    : results(9)  = myarr(1) + myarr(2)   ' exact wraparound boundary
myarr(1) = 4999d : myarr(2) = 5000d    : results(10) = myarr(1) + myarr(2)   ' just below wraparound boundary
myarr(1) = 1234d : myarr(2) = 8766d    : results(11) = myarr(1) + myarr(2)   ' wraparound, arbitrary values
myarr(1) = 1234d : myarr(2) = 8765d    : results(12) = myarr(1) + myarr(2)   ' no wraparound, arbitrary values
myarr(1) = 45d : myarr(2) = 55d        : results(13) = myarr(1) + myarr(2)   ' two-digit carry chain
myarr(1) = 999d : myarr(2) = 999d      : results(14) = myarr(1) + myarr(2)   ' multi-digit carry, no wraparound
myarr(1) = 9000d : myarr(2) = 1000d    : results(15) = myarr(1) + myarr(2)   ' wraparound, round numbers

' Subtraction: borrow boundaries between BCD digits, and underflow wraparound
myarr(1) = 0d : myarr(2) = 0d          : results(16) = myarr(1) - myarr(2)   ' zero-zero
myarr(1) = 1d : myarr(2) = 0d          : results(17) = myarr(1) - myarr(2)   ' one-zero
myarr(1) = 0d : myarr(2) = 1d          : results(18) = myarr(1) - myarr(2)   ' underflow wraparound
myarr(1) = 10d : myarr(2) = 1d         : results(19) = myarr(1) - myarr(2)   ' borrow from tens digit
myarr(1) = 100d : myarr(2) = 1d        : results(20) = myarr(1) - myarr(2)   ' borrow from hundreds digit
myarr(1) = 1000d : myarr(2) = 1d       : results(21) = myarr(1) - myarr(2)   ' borrow from thousands digit
myarr(1) = 9999d : myarr(2) = 9999d    : results(22) = myarr(1) - myarr(2)   ' max-max, zero
myarr(1) = 9999d : myarr(2) = 1d       : results(23) = myarr(1) - myarr(2)   ' near max, no underflow
myarr(1) = 5000d : myarr(2) = 5000d    : results(24) = myarr(1) - myarr(2)   ' equal operands, zero
myarr(1) = 5000d : myarr(2) = 1d       : results(25) = myarr(1) - myarr(2)   ' borrow chain
myarr(1) = 2d : myarr(2) = 3d          : results(26) = myarr(1) - myarr(2)   ' underflow by one
myarr(1) = 9000d : myarr(2) = 9001d    : results(27) = myarr(1) - myarr(2)   ' underflow near boundary
myarr(1) = 100d : myarr(2) = 99d       : results(28) = myarr(1) - myarr(2)   ' no borrow, small diff
myarr(1) = 100d : myarr(2) = 100d      : results(29) = myarr(1) - myarr(2)   ' equal operands, zero
myarr(1) = 45d : myarr(2) = 55d        : results(30) = myarr(1) - myarr(2)   ' underflow with two-digit borrow
myarr(1) = 1000d : myarr(2) = 999d     : results(31) = myarr(1) - myarr(2)   ' borrow across three-digit boundary

' Addition: filler generated by repeated accumulation (wraps several times)
myarr(3) = 137d : myarr(4) = 271d
FOR i = 0 TO 47
	myarr(3) = myarr(3) + myarr(4)
	results(32 + i) = myarr(3)
NEXT i

' Subtraction: filler generated by repeated accumulation (wraps several times)
myarr(3) = 9999d : myarr(4) = 271d
FOR i = 0 TO 47
	myarr(3) = myarr(3) - myarr(4)
	results(80 + i) = myarr(3)
NEXT i
