REM -- XC=BASIC built-in function headers

REM -- Math functions
DECLARE FUNCTION ABS AS BYTE (num AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION ABS AS INTEGER (num AS INTEGER) SHARED STATIC INLINE
DECLARE FUNCTION ABS AS WORD (num AS WORD) SHARED STATIC INLINE
DECLARE FUNCTION ABS AS LONG (num AS LONG) SHARED STATIC INLINE
DECLARE FUNCTION ABS AS FLOAT (num AS FLOAT) SHARED STATIC INLINE
DECLARE FUNCTION ATN AS FLOAT (num AS FLOAT) SHARED STATIC
DECLARE FUNCTION TAN AS FLOAT (num AS FLOAT) SHARED STATIC
DECLARE FUNCTION COS AS FLOAT (num AS FLOAT) SHARED STATIC
DECLARE FUNCTION SIN AS FLOAT (num AS FLOAT) SHARED STATIC
DECLARE FUNCTION EXP AS FLOAT (num AS FLOAT) SHARED STATIC
DECLARE FUNCTION LOG AS FLOAT (num AS FLOAT) SHARED STATIC
DECLARE FUNCTION RND AS FLOAT (num AS INTEGER) SHARED STATIC
DECLARE FUNCTION SGN AS INTEGER (num AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INTEGER (num AS INTEGER) SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INTEGER (num AS WORD) SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INTEGER (num AS LONG) SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INTEGER (num AS FLOAT) SHARED STATIC INLINE
DECLARE FUNCTION SQR AS BYTE (num AS BYTE) SHARED STATIC
DECLARE FUNCTION SQR AS INTEGER (num AS INTEGER) SHARED STATIC
DECLARE FUNCTION SQR AS WORD (num AS WORD) SHARED STATIC
DECLARE FUNCTION SQR AS LONG (num AS LONG) SHARED STATIC
DECLARE FUNCTION SQR AS FLOAT (num AS FLOAT) SHARED STATIC

REM -- Memory functions
DECLARE FUNCTION PEEK AS BYTE (address AS WORD) SHARED STATIC INLINE

REM -- String functions
DECLARE FUNCTION LEFT$ AS STRING (instr$ AS STRING, length AS BYTE) SHARED STATIC
DECLARE FUNCTION RIGHT$ AS STRING (instr$ AS STRING, length AS BYTE) SHARED STATIC
DECLARE FUNCTION MID$ AS STRING (instr$ AS STRING, pos AS BYTE, length AS BYTE) SHARED STATIC
DECLARE FUNCTION LEN AS BYTE (instr$ AS STRING) SHARED STATIC
DECLARE FUNCTION CHR$ AS STRING (charcode AS BYTE) SHARED STATIC
DECLARE FUNCTION ASC AS BYTE (char$ AS STRING) SHARED STATIC
DECLARE FUNCTION SPC AS STRING (length AS BYTE) SHARED STATIC
DECLARE FUNCTION STR$ AS STRING (number AS BYTE) SHARED STATIC
DECLARE FUNCTION STR$ AS STRING (number AS INTEGER) SHARED STATIC
DECLARE FUNCTION STR$ AS STRING (number AS WORD) SHARED STATIC
DECLARE FUNCTION STR$ AS STRING (number AS LONG) SHARED STATIC
DECLARE FUNCTION STR$ AS STRING (number AS FLOAT) SHARED STATIC
DECLARE FUNCTION STR$ AS STRING (number AS DECIMAL) SHARED STATIC
DECLARE FUNCTION VAL AS FLOAT (instr$ AS string) SHARED STATIC

REM -- Type Conversion
DECLARE FUNCTION CBYTE AS BYTE (number AS INTEGER) SHARED STATIC INLINE
DECLARE FUNCTION CBYTE AS BYTE (number AS WORD) SHARED STATIC INLINE
DECLARE FUNCTION CBYTE AS BYTE (number AS LONG) SHARED STATIC INLINE
DECLARE FUNCTION CBYTE AS BYTE (number AS FLOAT) SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INTEGER (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INTEGER (number AS WORD) SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INTEGER (number AS LONG) SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INTEGER (number AS FLOAT) SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS INTEGER) SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS LONG) SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS FLOAT) SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS INTEGER) SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS WORD) SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS FLOAT) SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS INTEGER) SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS WORD) SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS LONG) SHARED STATIC INLINE