REM -- XC=BASIC built-in function headers

REM -- Math functions
DECLARE FUNCTION ABS AS BYTE (num AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION ABS AS INT (num AS INT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION ABS AS WORD (num AS WORD) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION ABS AS LONG (num AS LONG) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION ABS AS FLOAT (num AS FLOAT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION RNDL AS LONG () SHARED STATIC INLINE
DECLARE FUNCTION RND AS FLOAT () SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION SGN AS INT (num AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INT (num AS INT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INT (num AS WORD) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INT (num AS LONG) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION SGN AS INT (num AS FLOAT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION SQR AS BYTE (num AS BYTE) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION SQR AS INT (num AS INT) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION SQR AS WORD (num AS WORD) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION SQR AS LONG (num AS LONG) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION SQR AS FLOAT (num AS FLOAT) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION POW AS FLOAT (base AS FLOAT, exp AS FLOAT) SHARED STATIC INLINE
DECLARE FUNCTION POW AS LONG (base AS INT, exp AS BYTE) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION EXP AS FLOAT (num AS FLOAT) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION LOG AS FLOAT (num AS FLOAT) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION INT AS FLOAT (num AS FLOAT) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION MOD AS BYTE (x AS BYTE, y AS BYTE) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION MOD AS INT (x AS INT, y AS INT) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION MOD AS WORD (x AS WORD, y AS WORD) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION MOD AS LONG (x AS LONG, y AS LONG) OVERRIDE SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION MOD AS FLOAT (x AS FLOAT, y AS float) OVERRIDE SHARED STATIC INLINE

REM -- Trigonometric functions
DECLARE FUNCTION ATN AS FLOAT (num AS FLOAT) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION TAN AS FLOAT (num AS FLOAT) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION COS AS FLOAT (num AS FLOAT) SHARED STATIC INLINE : REM TODO
DECLARE FUNCTION SIN AS FLOAT (num AS FLOAT) SHARED STATIC INLINE : REM TODO

REM -- System and IO functions
DECLARE FUNCTION PEEK AS BYTE (address AS WORD) SHARED STATIC INLINE
DECLARE FUNCTION TI AS LONG () SHARED STATIC INLINE
DECLARE FUNCTION ST AS BYTE () SHARED STATIC INLINE
DECLARE FUNCTION CSRLIN AS BYTE () SHARED STATIC INLINE
DECLARE FUNCTION POS AS BYTE () SHARED STATIC INLINE

REM -- String functions
DECLARE FUNCTION LEFT$ AS STRING (instr$ AS STRING, length AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION RIGHT$ AS STRING (instr$ AS STRING, length AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION MID$ AS STRING (instr$ AS STRING, pos AS BYTE, length AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION LEN AS BYTE (instr$ AS STRING) SHARED STATIC INLINE
DECLARE FUNCTION CHR$ AS STRING (charcode AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION ASC AS BYTE (char$ AS STRING) SHARED STATIC INLINE
DECLARE FUNCTION STR$ AS STRING (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION STR$ AS STRING (number AS INT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION STR$ AS STRING (number AS WORD) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION STR$ AS STRING (number AS LONG) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION STR$ AS STRING (number AS FLOAT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION STR$ AS STRING (number AS DECIMAL) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION VAL AS FLOAT (instr$ AS string) SHARED STATIC INLINE
DECLARE FUNCTION LCASE$ AS STRING (instr$ AS STRING) SHARED STATIC INLINE
DECLARE FUNCTION UCASE$ AS STRING (instr$ AS STRING) SHARED STATIC INLINE

REM -- Type Conversion
DECLARE FUNCTION CBYTE AS BYTE (number AS INT) SHARED STATIC INLINE
DECLARE FUNCTION CBYTE AS BYTE (number AS WORD) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CBYTE AS BYTE (number AS LONG) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CBYTE AS BYTE (number AS FLOAT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INT (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INT (number AS WORD) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INT (number AS LONG) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CINT AS INT (number AS FLOAT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS INT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS LONG) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CWORD AS WORD (number AS FLOAT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS INT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS WORD) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CLONG AS LONG (number AS FLOAT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS INT) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS WORD) OVERRIDE SHARED STATIC INLINE
DECLARE FUNCTION CFLOAT AS FLOAT (number AS LONG) OVERRIDE SHARED STATIC INLINE