'Graphics
DECLARE FUNCTION SCAN AS WORD () SHARED STATIC INLINE

'IO
DECLARE FUNCTION JOY AS BYTE (number AS BYTE) SHARED STATIC INLINE
DECLARE FUNCTION TI AS LONG () SHARED STATIC INLINE
DECLARE FUNCTION KEY AS BYTE (scancode AS WORD) SHARED STATIC INLINE