'Sprites
DECLARE FUNCTION SPRITEHIT AS BYTE (sprno AS BYTE) SHARED STATIC INLINE
'DECLARE FUNCTION SPRITEHITBG AS BYTE (sprno AS BYTE) SHARED STATIC INLINE

'Graphics
DECLARE FUNCTION SCAN AS WORD () SHARED STATIC INLINE

'IO
DECLARE FUNCTION JOY AS WORD (number AS BYTE) SHARED STATIC INLINE