INCLUDE "keycodes_cx64_common.bas"

' Keyboard scancodes of C64/C128 for KEY() function

' Printable characters
SHARED CONST KEY_ARROW_LEFT = $7F02
SHARED CONST KEY_ARROW_UP = $BF40
SHARED CONST KEY_MINUS = $DF40
SHARED CONST KEY_PLUS = $DF01
SHARED CONST KEY_POUND = $BF01

' Control keys
SHARED CONST KEY_CURSOR_DOWN = $FE80
SHARED CONST KEY_CURSOR_RIGHT = $FE04
SHARED CONST KEY_HOME = $BF08
SHARED CONST KEY_SHIFT_LEFT = $FD80
SHARED CONST KEY_SHIFT_RIGHT = $BF10

' Function keys
SHARED CONST KEY_F3 = $FE20
SHARED CONST KEY_F5 = $FE40
SHARED CONST KEY_F7 = $FE08
