INCLUDE "keycodes_pet_common.bas"

' Keyboard scancodes of PET/CBM business keyboard for KEY() function

' Numbers
SHARED CONST KEY_1 = $F101
SHARED CONST KEY_2 = $F001
SHARED CONST KEY_3 = $F902
SHARED CONST KEY_4 = $F102
SHARED CONST KEY_5 = $F002
SHARED CONST KEY_6 = $F904
SHARED CONST KEY_7 = $F104
SHARED CONST KEY_8 = $F004
SHARED CONST KEY_9 = $F908
SHARED CONST KEY_0 = $F108

' Letters
SHARED CONST KEY_A = $F301
' KEY_B: see keycodes_pet_common.bas
' KEY_C: see keycodes_pet_common.bas
SHARED CONST KEY_D = $F302
SHARED CONST KEY_E = $F502
SHARED CONST KEY_F = $F204
SHARED CONST KEY_G = $F304
SHARED CONST KEY_H = $F208
SHARED CONST KEY_I = $F420
SHARED CONST KEY_J = $F308
SHARED CONST KEY_K = $F220
SHARED CONST KEY_L = $F320
SHARED CONST KEY_M = $F808
' KEY_N: see keycodes_pet_common.bas
SHARED CONST KEY_O = $F520
SHARED CONST KEY_P = $F440
SHARED CONST KEY_Q = $F501
SHARED CONST KEY_R = $F404
SHARED CONST KEY_S = $F202
SHARED CONST KEY_T = $F504
SHARED CONST KEY_U = $F508
' KEY_V: see keycodes_pet_common.bas
SHARED CONST KEY_W = $F402
SHARED CONST KEY_X = $F802
SHARED CONST KEY_Y = $F408
SHARED CONST KEY_Z = $F701

' Printable characters
SHARED CONST KEY_ARROW_LEFT = $F901
SHARED CONST KEY_ARROW_UP = $F120
' KEY_AT: see keycodes_pet_business_[uk/us].bas
' KEY_BACKSLASH: see keycodes_pet_business_[uk/us].bas
' KEY_BRACKET_LEFT: see keycodes_pet_business_[uk/us].bas
' KEY_BRACKET_RIGHT: see keycodes_pet_business_[uk/us].bas
SHARED CONST KEY_COLON = $F920
' KEY_COMMA: see keycodes_pet_common.bas
SHARED CONST KEY_DOT = $F608
SHARED CONST KEY_MINUS = $F008
SHARED CONST KEY_RETURN = $F310
' KEY_SEMICOLON: see keycodes_pet_business_[uk/us].bas
SHARED CONST KEY_SLASH = $F840
SHARED CONST KEY_SPACE = $F804
SHARED CONST KEY_TAB = $F401

' Control keys
SHARED CONST KEY_CURSOR_DOWN = $F510
SHARED CONST KEY_CURSOR_RIGHT = $F020
SHARED CONST KEY_DEL = $F480
SHARED CONST KEY_ESC = $F201
SHARED CONST KEY_HOME = $F810
SHARED CONST KEY_REPEAT = $F740
SHARED CONST KEY_REVERSE = $F801
SHARED CONST KEY_SHIFT_LEFT = $F601
SHARED CONST KEY_SHIFT_RIGHT = $F640
' KEY_STOP: see keycodes_pet_common.bas

' Keypad
SHARED CONST KEY_KP_1 = $F880
SHARED CONST KEY_KP_2 = $F780
SHARED CONST KEY_KP_3 = $F680
SHARED CONST KEY_KP_4 = $F580
SHARED CONST KEY_KP_5 = $F280
SHARED CONST KEY_KP_6 = $F380
SHARED CONST KEY_KP_7 = $F110
SHARED CONST KEY_KP_8 = $F010
SHARED CONST KEY_KP_9 = $F180
SHARED CONST KEY_KP_0 = $F710
SHARED CONST KEY_KP_DOT = $F610
