INCLUDE "keycodes_cx64_common.bas"

' Keyboard scancodes of Commodore 264 series for KEY() function

' Printable characters
SHARED CONST KEY_AT = $DF40
SHARED CONST KEY_PLUS = $BF40
SHARED CONST KEY_POUND = $FE04

' Control keys
SHARED CONST KEY_CURSOR_DOWN = $DF01
SHARED CONST KEY_CURSOR_LEFT = $BF01
SHARED CONST KEY_CURSOR_RIGHT = $BF08
SHARED CONST KEY_CURSOR_UP = $DF08
SHARED CONST KEY_ESC = $BF10
SHARED CONST KEY_HOME = $7F02
SHARED CONST KEY_SHIFT = $FD80

' Function keys
SHARED CONST KEY_F2 = $FE20
SHARED CONST KEY_F3 = $FE40
SHARED CONST KEY_HELP = $FE08
