INCLUDE "keycodes_pet_common.bas"

' Keyboard scancodes of PET/CBM chiclet & graphics keyboard for KEY() function

' Numbers
SHARED CONST KEY_1 = $F640
SHARED CONST KEY_2 = $F740
SHARED CONST KEY_3 = $F680
SHARED CONST KEY_4 = $F440
SHARED CONST KEY_5 = $F540
SHARED CONST KEY_6 = $F480
SHARED CONST KEY_7 = $F240
SHARED CONST KEY_8 = $F340
SHARED CONST KEY_9 = $F280
SHARED CONST KEY_0 = $F840

' Letters
SHARED CONST KEY_A = $F401
' KEY_B: see keyboard_pet_common.bas
' KEY_C: see keyboard_pet_common.bas
SHARED CONST KEY_D = $F402
SHARED CONST KEY_E = $F202
SHARED CONST KEY_F = $F502
SHARED CONST KEY_G = $F404
SHARED CONST KEY_H = $F504
SHARED CONST KEY_I = $F308
SHARED CONST KEY_J = $F408
SHARED CONST KEY_K = $F508
SHARED CONST KEY_L = $F410
SHARED CONST KEY_M = $F608
' KEY_N: see keyboard_pet_common.bas
SHARED CONST KEY_O = $F210
SHARED CONST KEY_P = $F310
SHARED CONST KEY_Q = $F201
SHARED CONST KEY_R = $F302
SHARED CONST KEY_S = $F501
SHARED CONST KEY_T = $F204
SHARED CONST KEY_U = $F208
' KEY_V: see keyboard_pet_common.bas
SHARED CONST KEY_W = $F301
SHARED CONST KEY_X = $F701
SHARED CONST KEY_Y = $F304
SHARED CONST KEY_Z = $F601

' Printable characters
SHARED CONST KEY_AMPERSAND = $F008
SHARED CONST KEY_APOSTROPHE = $F104
SHARED CONST KEY_ARROW_LEFT = $F020
SHARED CONST KEY_ARROW_UP = $F220
SHARED CONST KEY_ASTERISK = $F580
SHARED CONST KEY_AT = $F802
SHARED CONST KEY_BACKSLASH = $F108
SHARED CONST KEY_BRACKET_LEFT = $F902
SHARED CONST KEY_BRACKET_RIGHT = $F804
SHARED CONST KEY_COLON = $F510
' KEY_COMMA: see keyboard_pet_common.bas
SHARED CONST KEY_DOLLAR = $F102
SHARED CONST KEY_DOT = $F940
SHARED CONST KEY_EQUALS = $F980
SHARED CONST KEY_EXCLAMATION_MARK = $F001
SHARED CONST KEY_GREATER_THAN = $F810
SHARED CONST KEY_HASH = $F002
SHARED CONST KEY_LESS_THAN = $F908
SHARED CONST KEY_MINUS = $F880
SHARED CONST KEY_PARENTHESIS_LEFT = $F010
SHARED CONST KEY_PARENTHESIS_RIGHTT = $F110
SHARED CONST KEY_PERCENT = $F004
SHARED CONST KEY_PLUS = $F780
SHARED CONST KEY_QUESTION_MARK = $F710
SHARED CONST KEY_QUOTATION_MARK = $F101
SHARED CONST KEY_RETURN = $F620
SHARED CONST KEY_SEMICOLON = $F610
SHARED CONST KEY_SLASH = $F380
SHARED CONST KEY_SPACE = $F904

' Control keys
SHARED CONST KEY_CURSOR_DOWN = $F140
SHARED CONST KEY_CURSOR_RIGHT = $F080
SHARED CONST KEY_DEL = $F180
SHARED CONST KEY_HOME = $F040
SHARED CONST KEY_REVERSE = $F901
SHARED CONST KEY_SHIFT_LEFT = $F801
SHARED CONST KEY_SHIFT_RIGHT = $F820
' KEY_STOP: see keyboard_pet_common.bas
