INCLUDE "keycodes_vic20_common.bas"

' Keyboard scancodes for KEY() function
' common to C64/C128 and 264 series keyboards

' Numbers
SHARED CONST KEY_1 = $7F01
SHARED CONST KEY_2 = $7F08
SHARED CONST KEY_3 = $FD01
SHARED CONST KEY_4 = $FD08
SHARED CONST KEY_5 = $FB01
SHARED CONST KEY_6 = $FB08
SHARED CONST KEY_7 = $F701
SHARED CONST KEY_8 = $F708
SHARED CONST KEY_9 = $EF01
SHARED CONST KEY_0 = $EF08

' Letters
SHARED CONST KEY_A = $FD04
SHARED CONST KEY_B = $F710
SHARED CONST KEY_C = $FB10
' KEY_D: see keycodes_vic20_common.bas
SHARED CONST KEY_E = $FD40
SHARED CONST KEY_F = $FB20
SHARED CONST KEY_G = $F704
SHARED CONST KEY_H = $F720
SHARED CONST KEY_I = $EF02
SHARED CONST KEY_J = $EF04
SHARED CONST KEY_K = $EF20
SHARED CONST KEY_L = $DF04
' KEY_M: see keycodes_vic20_common.bas
SHARED CONST KEY_N = $EF80
SHARED CONST KEY_O = $EF40
SHARED CONST KEY_P = $DF02
SHARED CONST KEY_Q = $7F40
SHARED CONST KEY_R = $FB02
SHARED CONST KEY_S = $FD20
SHARED CONST KEY_T = $FB40
SHARED CONST KEY_U = $F740
SHARED CONST KEY_V = $F780
' KEY_W: see keycodes_vic20_common.bas
SHARED CONST KEY_X = $FB80
SHARED CONST KEY_Y = $F702
SHARED CONST KEY_Z = $FD10

' Printable characters
SHARED CONST KEY_ASTERISK = $BF02
' KEY_COLON: see keycodes_vic20_common.bas
SHARED CONST KEY_COMMA = $DF80
SHARED CONST KEY_COMMODORE = $7F20
SHARED CONST KEY_DOT = $DF10
SHARED CONST KEY_EQUALS = $BF20
SHARED CONST KEY_RETURN = $FE02
SHARED CONST KEY_SEMICOLON = $BF04
SHARED CONST KEY_SLASH = $BF80
SHARED CONST KEY_SPACE = $7F10

' Control keys
SHARED CONST KEY_CTRL = $7F04
SHARED CONST KEY_DEL = $FE01
SHARED CONST KEY_STOP = $7F80

' Function keys
SHARED CONST KEY_F1 = $FE10
