INCLUDE "keycodes_vic20_common.bas"

' Keyboard scancodes of VIC 1001/VC 20/VIC 20 for KEY() function

' Numbers
SHARED CONST KEY_1 = $FE01
SHARED CONST KEY_2 = $F701
SHARED CONST KEY_3 = $FE02
SHARED CONST KEY_4 = $7F02
SHARED CONST KEY_5 = $FE04
SHARED CONST KEY_6 = $7F04
SHARED CONST KEY_7 = $FE08
SHARED CONST KEY_8 = $7F08
SHARED CONST KEY_9 = $FE10
SHARED CONST KEY_0 = $7F10

' Letters
SHARED CONST KEY_A = $FB02
SHARED CONST KEY_B = $EF08
SHARED CONST KEY_C = $EF04
' KEY_D: see keycodes_vic20_common.bas
SHARED CONST KEY_E = $BF02
SHARED CONST KEY_F = $DF04
SHARED CONST KEY_G = $FB08
SHARED CONST KEY_H = $DF08
SHARED CONST KEY_I = $FD10
SHARED CONST KEY_J = $FB10
SHARED CONST KEY_K = $DF10
SHARED CONST KEY_L = $FB20
' KEY_M: see keycodes_vic20_common.bas
SHARED CONST KEY_N = $F710
SHARED CONST KEY_O = $BF10
SHARED CONST KEY_P = $FD20
SHARED CONST KEY_Q = $BF01
SHARED CONST KEY_R = $FD04
SHARED CONST KEY_S = $DF02
SHARED CONST KEY_T = $BF04
SHARED CONST KEY_U = $BF08
SHARED CONST KEY_V = $F708
' KEY_W: see keycodes_vic20_common.bas
SHARED CONST KEY_X = $F704
SHARED CONST KEY_Y = $FD08
SHARED CONST KEY_Z = $EF02

' Printable characters
SHARED CONST KEY_ARROW_LEFT = $FD01
SHARED CONST KEY_ARROW_UP = $BF40
SHARED CONST KEY_ASTERISK = $FD40
' KEY_COLON: see keycodes_vic20_common.bas
SHARED CONST KEY_COMMA = $7F20
SHARED CONST KEY_COMMODORE = $DF01
SHARED CONST KEY_DOT = $EF20
SHARED CONST KEY_EQUALS = $DF40
SHARED CONST KEY_MINUS = $BF20
SHARED CONST KEY_PLUS = $FE20
SHARED CONST KEY_POUND = $FE40
SHARED CONST KEY_RETURN = $FD80
SHARED CONST KEY_SEMICOLON = $FB40
SHARED CONST KEY_SLASH = $F740
SHARED CONST KEY_SPACE = $EF01

' Control keys
SHARED CONST KEY_CTRL = $FB01
SHARED CONST KEY_CURSOR_DOWN = $F780
SHARED CONST KEY_CURSOR_RIGHT = $FB80
SHARED CONST KEY_DEL = $FE80
SHARED CONST KEY_HOME = $7F40
SHARED CONST KEY_SHIFT_LEFT = $F702
SHARED CONST KEY_SHIFT_RIGHT = $EF40
SHARED CONST KEY_STOP = $7F01

' Function keys
SHARED CONST KEY_F1 = $DF80
SHARED CONST KEY_F3 = $BF80
SHARED CONST KEY_F5 = $7F80
SHARED CONST KEY_F7 = $EF80
