' Tests memory commands with constant arguments in XC=BASIC
' MONITOR: m c000 c07f

CONST BASE = $C000
CONST ZERO = 0
CONST PAGE_LEN = 128
CONST FILL_LEN = 16
CONST FILL_VALUE = $11
CONST BYTE_ADDR = $C002
CONST BYTE_COPY_ADDR = $C003
CONST BYTE_VALUE = $22
CONST WORD_ADDR = $C004
CONST WORD_COPY_ADDR = $C012
CONST WORD_VALUE = $3456
CONST COPY_SOURCE = $C020
CONST COPY_DEST = $C030
CONST SHIFT_SOURCE = $C040
CONST SHIFT_DEST = $C050
CONST MOVE_LEN = 8

DIM results(128) AS BYTE @ BASE

MEMSET BASE, PAGE_LEN, ZERO
MEMSET BASE, FILL_LEN, FILL_VALUE

POKE BYTE_ADDR, BYTE_VALUE
POKE BYTE_COPY_ADDR, PEEK(BYTE_ADDR)
results(16) = PEEK(BYTE_ADDR)

DOKE WORD_ADDR, WORD_VALUE
DOKE WORD_COPY_ADDR, DEEK(WORD_ADDR)

POKE COPY_SOURCE, 1
POKE COPY_SOURCE + 1, 2
POKE COPY_SOURCE + 2, 3
POKE COPY_SOURCE + 3, 4
POKE COPY_SOURCE + 4, 5
POKE COPY_SOURCE + 5, 6
POKE COPY_SOURCE + 6, 7
POKE COPY_SOURCE + 7, 8
MEMCPY COPY_SOURCE, COPY_DEST, MOVE_LEN
' Overlapping copy down: $C021-$C027 -> $C020-$C026
MEMCPY COPY_SOURCE + 1, COPY_SOURCE, MOVE_LEN - 1

POKE SHIFT_SOURCE, 9
POKE SHIFT_SOURCE + 1, 10
POKE SHIFT_SOURCE + 2, 11
POKE SHIFT_SOURCE + 3, 12
POKE SHIFT_SOURCE + 4, 13
POKE SHIFT_SOURCE + 5, 14
POKE SHIFT_SOURCE + 6, 15
POKE SHIFT_SOURCE + 7, 16
MEMSHIFT SHIFT_SOURCE, SHIFT_DEST, MOVE_LEN
' Overlapping shift up: $C040-$C046 -> $C041-$C047
MEMSHIFT SHIFT_SOURCE, SHIFT_SOURCE + 1, MOVE_LEN - 1